language: csharp
solution: TestWebAPI.sln
mono: latest
install:
 - travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./TestWebAPI/TestWebAPI.sln
script
 - xbuild /p:Configuration=Release ./TestWebAPI/TestWebAPI.sln
