language: csharp
solution: TestWebAPI.sln
mono: latest
install:
 - travis_retry nuget restore -source "https://www.nuget.org/api/v2" TestWebAPI.sln
script:
 - xbuild /p:Configuration=Custom TestWebAPI.sln
