addons:
  apt:
    sources:
    - mono-nightly
    packages:
    - mono-devel
install:
  - sudo apt-get install nunit-console
  - nuget restore TestWebAPI.sln

script:
  - msbuild /p:Configuration=Test TestWebAPI.sln
  - nunit-console TestWebAPI.Tests/bin/Test/TestWebAPI.Tests.dll
