language: csharp
solution: TestWebAPI.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore TestWebAPI.sln

script:
  - msbuild /p:Configuration=Custom TestWebAPI.sln
  - nunit-console TestWebAPI.Tests/bin/Debug/TestWebAPI.Tests.dll
