addons:
  apt:
    sources:
    - mono-nightly
    packages:
    - mono-devel
before_install:
  - git submodule update --init --recursive
install:
  - sudo apt-get install nunit-console
  #- nuget restore TestWebAPI.sln
script:
  - xbuild /p:Configuration=Test TestWebAPI.sln
  - nunit-console TestWebAPI.Tests/bin/Test/TestWebAPI.Tests.dll
